apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-rwn
  labels:
    machineconfiguration.openshift.io/role: worker-rwn
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker-rwn, worker],
        }
  paused: false
  nodeSelector:
    matchLabels:
      node.kubernetes.io/role: "rwn"
